### ISSUE TITLE
webapp issues

### ISSUE THREAD

**Issue by dnalor** [shuLhan/rescached-go#10]
First of all, thanks for writing this.

I'd like to point out some issues in the webapp:
- links are absolute and not relative
- the built-in webserver seems to ignore the "Accept-Encoding" header and always sends gzipped output
```
$ wget --header='Accept-Encoding: ' "http://127.0.0.1:5380"
$ file index.html 
index.html: gzip compressed data, original size modulo 2^32 5235
```
combined, this means putting it behind a reverse proxy is basically impossible
- the "Remove from cache" button does nothing. On the browser console, I see:
```
Uncaught ReferenceError: doRemove is not defined
    onclick http://server:5380/:1
```
- minor cosmetic issue (Linux, both Firefox and Vivaldi):
![rc](https://user-images.githubusercontent.com/26877697/145689194-20bad572-7449-4c09-a08c-ff70f0b6ce56.png)

**Comment by shuLhan** [comment]
Hi @dnalor,

Thanks for reporting the issues. I will take a look later.

**Comment by shuLhan** [comment]
@dnalor Should be fixed now. Let me know if you still or have any other issue.
