### ISSUE TITLE
AUR package installation fails: wrong man-directory created in Makefile

### ISSUE THREAD

**Issue by astier** [shuLhan/rescached-go#4]
The installation of the aur package [rescached-git](https://aur.archlinux.org/packages/rescached-git/) fails with the following error:

```
cp: cannot create regular file '/home/user/rescached-git/pkg/rescached-git/usr/share/man/man1/': Not a directory
make: *** [Makefile:104: install] Error 1
```

The problem is that the `man1` directory is not created. Instead `man{1,5}` is created. The problem is:

https://github.com/shuLhan/rescached-go/blob/e9d4cd48f48c82b5baa568c64735a5c969c2182b/Makefile#L105

**Comment by shulhan-tokenomy** [comment]
Ah I see, thank you for reporting. Just curious, what is your default shell?

**Comment by shuLhan** [comment]
Ah I see, thank you for reporting.  Just curious, what is your default shell?

**Comment by astier** [comment]
My login-shell is dash which I define via

```sh
chsh -s /bin/dash
sudo ln -sfT dash /usr/bin/sh
```

My interactive-shell however is bash which I define in my tmux.config and in my terminal-settings.

**Comment by shuLhan** [comment]
@astier I have fix in the latest commit.  Feel free to close if its already fixed for you.  Thank you.

**Comment by astier** [comment]
This solved it. Thanks.

**Comment by astier** [comment]
Just dont forget to update the aur-package.
