### ISSUE TITLE
AUR package not building: share/go.mod: no such file or directory

### ISSUE THREAD

**Issue by bcookatpcsd** [shuLhan/rescached-go#6]
Could not get the aur package to build with yay, same error with _AUR files from current (

==> Making package: rescached-git 3.0.0.r0.g94be622-1 (Fri 08 May 2020 08:48:24 AM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning rescached-git git repo...
Cloning into bare repository '/home/bcook/go/src/github.com/shuLhan/rescached-go/_AUR/rescached-git'...
remote: Enumerating objects: 176, done.
remote: Counting objects: 100% (176/176), done.
remote: Compressing objects: 100% (115/115), done.
remote: Total 1223 (delta 91), reused 133 (delta 60), pack-reused 1047
Receiving objects: 100% (1223/1223), 700.05 KiB | 6.67 MiB/s, done.
Resolving deltas: 100% (685/685), done.
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Creating working copy of rescached-git git repo...
Cloning into 'rescached-git'...
done.
==> Starting pkgver()...
==> Updated version: rescached-git 3.0.1.r0.gd44ef66-1
==> Starting build()...
>>
>> cleaning ...
>>
go: github.com/shuLhan/share@v0.15.0: parsing ../share/go.mod: open /home/user/go/src/github.com/shuLhan/rescached-go/_AUR/src/share/go.mod: no such file or directory
go: github.com/shuLhan/share@v0.15.0: parsing ../share/go.mod: open /home/user/go/src/github.com/shuLhan/rescached-go/_AUR/src/share/go.mod: no such file or directory
>>
>> make ...
>>
go: github.com/shuLhan/share@v0.15.0: parsing ../share/go.mod: open /home/user/go/src/github.com/shuLhan/rescached-go/_AUR/src/share/go.mod: no such file or directory
go: github.com/shuLhan/share@v0.15.0: parsing ../share/go.mod: open /home/user/go/src/github.com/shuLhan/rescached-go/_AUR/src/share/go.mod: no such file or directory
go: github.com/shuLhan/share@v0.15.0: parsing ../share/go.mod: open /home/user/go/src/github.com/shuLhan/rescached-go/_AUR/src/share/go.mod: no such file or directory
go: github.com/shuLhan/share@v0.15.0: parsing ../share/go.mod: open /home/user/go/src/github.com/shuLhan/rescached-go/_AUR/src/share/go.mod: no such file or directory
go: github.com/shuLhan/share@v0.15.0: parsing ../share/go.mod: open /home/user/go/src/github.com/shuLhan/rescached-go/_AUR/src/share/go.mod: no such file or directory
go: github.com/shuLhan/share@v0.15.0: parsing ../share/go.mod: open /home/user/go/src/github.com/shuLhan/rescached-go/_AUR/src/share/go.mod: no such file or directory
make: *** [Makefile:61: rescached] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:52: cover.out] Error 1
make: *** [Makefile:64: resolver] Error 1
make: *** [Makefile:67: resolverbench] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

share/go.mod does in fact not exist

git clone https://github.com/shuLhan/share.git in _AUR/src

fixes the issue.. 

I'm new to go so I do not understand how to tell go to import this, but this seems to be the solution. 

==> Leaving fakeroot environment.
==> Finished making: rescached-git 3.0.1.r0.gd44ef66-1 (Fri 08 May 2020 08:57:58 AM EDT)
==> Installing package rescached-git with pacman -U...

**Comment by shuLhan** [comment]
@bcookatpcsd Thanks for report. Seems like there is a replace directive in go.mod that I forgot to comment.

I will fix and push tomorrow.
