### ISSUE TITLE
AUR package is outdated

### ISSUE THREAD

**Issue by danielsouzat** [shuLhan/rescached-go#7]
It's building fine but version should be updated and dependency **go-pie** should be renamed to **go**  as the package was renamed in Arch (1 month ago I believe). And thanks for the software, so far I'm enjoying it!

**Comment by shuLhan** [comment]
@danielsouzat Thanks for reminding. I will update later.

**Comment by shuLhan** [comment]
@danielsouzat The new AUR version has been pushed. If you have any issue, do not hesitate to report it. Thank you.

**Comment by danielsouzat** [comment]
Installed it through AUR and all is good.
