### ISSUE TITLE
Optionally disable serving DoH and DoT

### ISSUE THREAD

**Issue by lbcnz** [shuLhan/rescached-go#8]
Right now there's no way to disable serving DNS over HTTPS and over TLS. It can be a problem because per default it will bind to port 443 and conflict with web servers. Although that's easy to solve by using a random port and it can even coexist in port 443 through a reverse proxy, as as home user, I don't really have a use case for it and it's a lot easier and almost as good to serve normal DNS over 53.

Nothing critical, just a very minor issue. Maybe that's already implemented or it's easy to implement.

**Comment by shuLhan** [comment]
@danielsouzat I belive I has implemented this on dev branch.  If we set the http.port and/or tls.port to 0 [1] it will not listen to DoH and DoT.

There are some pretty big changes on "dev" branch right now, including a web user interface to configure it on the fly. Let me see if I can cherry picked it to master.

[1] https://github.com/shuLhan/rescached-go/blob/dev/cmd/rescached/rescached.cfg

**Comment by danielsouzat** [comment]
On 3.0.2 it reverts to default ports when set to 0. As I said, it's just a minor nuisance. But it's nice that you have implemented or thinking on implementing that.

**Comment by shuLhan** [comment]
@danielsouzat Yes, v3.0.2 is still by default listening for DoH and DoT.  The one that disable it is currently reside in dev branch. I will let you know when its has been merged to master.

**Comment by shuLhan** [comment]
@lbcnz I think, if you try the latest git from AUR it will not listen to DoT and DoH anymore. But, I remind you, there are a lot of changes in the master branch right now that might or might not break.

Feel free to close if you think if its has been solved.

**Comment by lbcnz** [comment]
Sorry for taking so long. It is working as expected.
