### ISSUE TITLE
save the cache between the restarts

### ISSUE THREAD

**Issue by Oreolek** [shuLhan/rescached-go#9]
Why discard the good entries on restarts?

**Comment by shuLhan** [comment]
Hi Alex,

Thank you for using rescached and for your input.

The feature for saving and loading the existing cache has not been implemented in this new, rewritten version.

I will take a look and if I have time, we may have it in the next release.

**Comment by shuLhan** [comment]
Hi @Oreolek ,

The latest commit implement the feature to store/load caches from storage.

If you can help to test it, run `make deploy` if you use GNU/Linux or rebuild from AUR if you use Arch Linux.

**Comment by Oreolek** [comment]
Yup, thank you!
